version: "3.8"

services:
  app:
    container_name: docker-cl-example-minimum
    build:
      dockerfile: docker/Dockerfile-app
      context: .
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - .:/app:ro
      - /app/.qlot
