name: Build production image

on:
  push:
    branches: master
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build the latest image and push
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./standard
          file: ./standard/docker/Dockerfile-app-production
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/fukamachi/docker-cl-example-standard:latest
      - name: Build the release image
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./standard
          file: ./standard/docker/Dockerfile-app-production
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/fukamachi/docker-cl-example-standard:${{ steps.vars.outputs.tag }}
